version: '3.8'

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - ./migrations/init/up.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  db_data:

